# Generated by Django 6.0 on 2025-12-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvprocessor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
