# Generated by Django 6.0 on 2025-12-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvprocessor', '0002_rename_stock_name_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
