# Generated by Django 6.0 on 2025-12-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvprocessor', '0003_product_id_alter_product_stock'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_fce6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_price_fe467e_idx'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
